[package]
name = "exfiltrator-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-multipart = "0.6.0"
actix-web = "4.0.0"
futures = "0.3.16"
serde_json = "1.0.96"
uuid = "1.3.2"
